sample-python-app:
  name: sample-python-app
  type: python
  source_dir: .tests/mock/python-app
  package_type: tarball

sample-perl-app:
  name: sample-perl-app
  type: perl
  source_dir: .tests/mock/perl-app
  package_type: tarball